In [1]:
import numpy as np
np.random.seed(100)

import matplotlib.pyplot as plt
import time
import os
%matplotlib inline

from keras.callbacks import LearningRateScheduler

Using TensorFlow backend.

In [2]:
import sys
sys.path.insert(0, '..')
sys.path.insert(0, '../src/')

# import evaluation_bk as evaluation
import evaluation
import training_utils
from src import TripletDataGenerator, TriNet
import data

## Load Data

In [3]:
sys.path.insert(0, '/home/gong/research/Video-Person-ReID')
import data_manager

In [4]:
mars = data_manager.Mars()

=> MARS loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # tracklets
  ------------------------------
  train    |   625 |     8298
  query    |   626 |     1980
  gallery  |   622 |     9330
  ------------------------------
  total    |  1251 |    19608
  number of images per tracklet: 2 ~ 920, average 59.5
  ------------------------------

In [3]:
P_param = 18
K_param = 4
img_dim = (256,128,3)

crop = True
flip = True

In [15]:
data_gen = data.MARS('test')

(1980,)
(10200,)
622

In [16]:
full_list = []
for pid in os.listdir("/home/gong/research/data/mars/bbox_test/"):
    if pid == "00-1":
        pid = -1
    else:
        pid = int(pid)
    if not pid in full_list:
        full_list.append(pid)

In [13]:
len(full_list)

625

In [14]:
len(data_gen.files_dict.keys())

625

In [31]:
for pid in full_list:
#     print(pid)
    if not pid in data_gen.files_dict.keys():
        print(pid)

782
640
1444
454
1062
152
1140
436
1252
6
944
1172
1138
1146

In [8]:
names = data_gen._get_names("/home/gong/research/MARS-evaluation/info/test_name.txt")

In [9]:
pid_list = []
for name in names:
    pid = name[:name.index('C')]
    if pid == "00-1":
        pid = -1
    else:
        pid = int(pid)
    if not pid in pid_list:
        pid_list.append(pid)

In [10]:
len(pid_list)

636

In [9]:
data_gen.track_info[-10:]

array([[509363, 509390,   1497,      5],
       [509391, 509508,   1497,      5],
       [509509, 509744,   1497,      5],
       [509745, 509768,   1499,      1],
       [509769, 509776,   1499,      1],
       [509777, 509797,   1499,      1],
       [509798, 509820,   1499,      1],
       [509821, 509844,   1499,      5],
       [509845, 509864,   1499,      5],
       [509865, 509914,   1499,      5]], dtype=int32)

In [13]:
import pandas as pd
data = pd.read_csv('../../MARS-evaluation/info/test_name.txt')

In [17]:
data_np = np.array(data).squeeze()

In [18]:
data_np

array(['00-1C1T0001F002.jpg', '00-1C1T0001F003.jpg',
       '00-1C1T0001F004.jpg', ..., '1500C5T0003F016.jpg',
       '1500C5T0003F017.jpg', '1500C5T0003F018.jpg'], dtype=object)

In [19]:
from scipy.io import loadmat
matdata = loadmat("/home/gong/research/MARS-evaluation/info/query_IDX.mat")

In [20]:
query_idx = matdata["query_IDX"][0]

In [21]:
query_idx

array([ 4130,  4138,  4146, ..., 12177, 12179, 12180], dtype=uint16)

In [22]:
track_test = loadmat("/home/gong/research/MARS-evaluation/info/tracks_test_info.mat")

In [34]:
# track_test["track_test_info"][:100]

In [32]:
np.unique(track_test["track_test_info"][:, 2])

array([  -1,    0,    2,    4,    6,    8,   10,   12,   14,   16,   18,
         22,   24,   26,   28,   32,   34,   36,   44,   46,   48,   50,
         52,   60,   62,   64,   66,   68,   72,   76,   78,   80,   82,
         92,   94,   96,  100,  104,  106,  110,  112,  116,  118,  120,
        128,  130,  132,  136,  142,  144,  146,  148,  150,  152,  154,
        156,  158,  160,  162,  166,  170,  172,  174,  176,  178,  182,
        184,  186,  188,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  216,  218,  220,  222,  224,  226,  228,  230,  232,
        236,  238,  240,  242,  244,  248,  252,  254,  256,  258,  260,
        262,  264,  266,  268,  270,  272,  274,  276,  278,  280,  282,
        284,  286,  288,  290,  292,  294,  296,  298,  300,  302,  304,
        306,  308,  310,  312,  314,  316,  318,  320,  322,  324,  326,
        328,  330,  332,  334,  336,  340,  342,  344,  346,  348,  350,
        352,  354,  358,  362,  364,  366,  368,  370,  372,  374,  376,
        378,  380,  384,  386,  388,  390,  394,  396,  400,  402,  404,
        406,  408,  410,  412,  414,  418,  420,  422,  424,  426,  428,
        430,  432,  434,  436,  438,  440,  442,  444,  446,  448,  450,
        452,  454,  456,  458,  460,  462,  464,  466,  468,  470,  472,
        474,  476,  478,  480,  482,  484,  486,  488,  490,  492,  494,
        496,  498,  500,  502,  506,  508,  512,  514,  516,  518,  520,
        522,  526,  530,  534,  538,  544,  546,  548,  550,  552,  554,
        556,  558,  560,  562,  564,  566,  568,  570,  572,  574,  578,
        580,  582,  584,  588,  590,  592,  594,  596,  598,  600,  602,
        604,  606,  608,  610,  612,  614,  616,  618,  620,  622,  624,
        626,  628,  630,  632,  634,  636,  638,  640,  642,  644,  646,
        648,  650,  652,  654,  656,  658,  662,  664,  666,  668,  670,
        672,  674,  676,  678,  680,  682,  684,  686,  688,  690,  692,
        694,  696,  698,  700,  702,  704,  706,  708,  710,  714,  716,
        718,  720,  722,  724,  726,  728,  730,  732,  734,  736,  738,
        740,  742,  744,  746,  750,  754,  756,  758,  760,  762,  764,
        766,  768,  770,  772,  774,  776,  778,  780,  782,  784,  786,
        788,  790,  792,  794,  796,  798,  800,  802,  804,  806,  808,
        810,  812,  814,  816,  818,  820,  822,  824,  826,  828,  830,
        832,  834,  838,  842,  844,  846,  848,  850,  852,  856,  858,
        860,  866,  868,  870,  872,  874,  876,  878,  880,  884,  886,
        888,  890,  892,  894,  896,  900,  902,  904,  908,  910,  912,
        914,  916,  918,  920,  922,  924,  926,  930,  932,  934,  936,
        942,  944,  946,  948,  950,  952,  954,  958,  960,  962,  964,
        966,  968,  970,  972,  974,  976,  978,  982,  984,  986,  988,
        990,  992,  994,  996,  998, 1000, 1002, 1004, 1008, 1010, 1012,
       1014, 1016, 1018, 1020, 1022, 1024, 1026, 1028, 1030, 1032, 1034,
       1038, 1040, 1042, 1044, 1052, 1054, 1058, 1062, 1064, 1068, 1070,
       1074, 1076, 1078, 1082, 1084, 1086, 1088, 1090, 1092, 1096, 1098,
       1100, 1102, 1104, 1108, 1110, 1112, 1116, 1118, 1120, 1122, 1124,
       1126, 1128, 1130, 1132, 1134, 1136, 1138, 1140, 1142, 1144, 1146,
       1148, 1150, 1152, 1154, 1156, 1158, 1164, 1172, 1174, 1176, 1178,
       1180, 1182, 1184, 1186, 1188, 1190, 1196, 1198, 1200, 1204, 1208,
       1214, 1216, 1222, 1224, 1226, 1228, 1230, 1234, 1236, 1238, 1240,
       1244, 1248, 1250, 1252, 1254, 1258, 1260, 1262, 1264, 1266, 1268,
       1270, 1272, 1274, 1276, 1278, 1280, 1282, 1286, 1288, 1290, 1292,
       1294, 1296, 1298, 1300, 1306, 1312, 1314, 1316, 1318, 1320, 1322,
       1324, 1326, 1330, 1332, 1336, 1338, 1340, 1342, 1344, 1348, 1350,
       1352, 1354, 1358, 1360, 1362, 1364, 1366, 1368, 1370, 1372, 1376,
       1378, 1380, 1382, 1384, 1388, 1390, 1392, 1394, 1396, 1398, 1402,
       1404, 1406, 1408, 1410, 1412, 1416, 1418, 1420, 1422, 1424, 1428,
       1430, 1432, 1434, 1436, 1438, 1440, 1442, 1444, 1448, 1452, 1454,
       1456, 1458, 1460, 1464, 1466, 1470, 1472, 1474, 1476, 1478, 1480,
       1482, 1484, 1486, 1488, 1490, 1492, 1494, 1496, 1500], dtype=int32)

In [36]:
np.unique(track_test["track_test_info"][query_idx-1, 2])

array([   2,    4,    6,    8,   10,   16,   18,   22,   24,   26,   28,
         32,   34,   36,   44,   46,   48,   50,   52,   60,   62,   64,
         66,   68,   72,   76,   78,   80,   82,   92,   94,   96,  100,
        104,  106,  110,  112,  116,  118,  120,  128,  130,  132,  136,
        142,  144,  146,  148,  150,  152,  156,  158,  160,  162,  170,
        172,  174,  176,  178,  182,  184,  186,  188,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  216,  218,  220,  222,
        224,  226,  228,  230,  232,  236,  238,  240,  242,  244,  248,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  310,  312,  314,  316,
        318,  320,  322,  324,  326,  328,  330,  332,  334,  336,  340,
        342,  344,  346,  348,  350,  352,  354,  358,  362,  364,  366,
        368,  370,  372,  374,  376,  378,  380,  384,  386,  388,  390,
        394,  396,  400,  402,  404,  406,  408,  410,  412,  414,  418,
        420,  422,  424,  426,  428,  430,  432,  434,  436,  438,  440,
        442,  444,  446,  448,  450,  452,  454,  456,  458,  460,  462,
        464,  466,  468,  470,  472,  474,  476,  478,  480,  482,  484,
        486,  488,  490,  492,  494,  496,  498,  500,  502,  506,  508,
        512,  514,  516,  518,  520,  522,  526,  530,  534,  538,  544,
        546,  548,  550,  552,  554,  556,  558,  560,  562,  564,  566,
        568,  570,  572,  574,  578,  580,  582,  584,  588,  590,  592,
        594,  596,  598,  600,  602,  604,  606,  608,  610,  612,  614,
        616,  618,  620,  622,  624,  626,  628,  630,  632,  634,  636,
        638,  640,  642,  644,  646,  648,  650,  652,  654,  656,  658,
        662,  664,  666,  668,  670,  672,  674,  676,  678,  680,  682,
        684,  686,  688,  690,  692,  694,  696,  698,  700,  702,  704,
        706,  708,  710,  714,  716,  718,  720,  722,  724,  726,  728,
        730,  732,  734,  736,  738,  740,  742,  744,  746,  750,  754,
        756,  758,  760,  762,  764,  766,  768,  770,  772,  774,  776,
        778,  780,  782,  784,  786,  788,  790,  792,  794,  796,  798,
        800,  802,  804,  806,  808,  810,  812,  814,  816,  818,  820,
        822,  824,  826,  828,  830,  832,  834,  838,  842,  844,  846,
        848,  850,  852,  856,  858,  860,  866,  868,  870,  872,  874,
        876,  878,  880,  884,  886,  888,  890,  892,  894,  896,  900,
        902,  904,  908,  910,  912,  914,  916,  918,  920,  922,  924,
        926,  930,  932,  934,  936,  942,  944,  946,  948,  950,  952,
        954,  958,  960,  962,  964,  966,  968,  970,  972,  974,  976,
        978,  984,  986,  988,  990,  992,  994,  996,  998, 1000, 1002,
       1004, 1008, 1010, 1012, 1014, 1016, 1018, 1020, 1022, 1024, 1026,
       1028, 1030, 1032, 1038, 1040, 1042, 1044, 1052, 1054, 1058, 1062,
       1064, 1068, 1070, 1074, 1076, 1078, 1082, 1084, 1086, 1088, 1090,
       1092, 1096, 1098, 1100, 1102, 1108, 1110, 1112, 1116, 1118, 1120,
       1122, 1124, 1126, 1128, 1130, 1132, 1134, 1136, 1138, 1140, 1142,
       1144, 1146, 1148, 1150, 1152, 1154, 1156, 1158, 1164, 1172, 1174,
       1176, 1178, 1180, 1182, 1184, 1186, 1188, 1190, 1196, 1198, 1200,
       1204, 1208, 1214, 1216, 1222, 1224, 1226, 1228, 1230, 1234, 1236,
       1238, 1240, 1244, 1248, 1250, 1252, 1254, 1258, 1260, 1262, 1264,
       1266, 1268, 1270, 1272, 1274, 1276, 1278, 1280, 1282, 1286, 1288,
       1290, 1292, 1294, 1296, 1298, 1300, 1306, 1312, 1314, 1316, 1318,
       1320, 1322, 1324, 1326, 1330, 1332, 1336, 1338, 1340, 1342, 1344,
       1348, 1350, 1352, 1358, 1360, 1362, 1364, 1366, 1368, 1370, 1372,
       1376, 1378, 1380, 1382, 1384, 1388, 1390, 1392, 1394, 1396, 1398,
       1402, 1404, 1406, 1408, 1410, 1412, 1416, 1418, 1420, 1422, 1424,
       1428, 1430, 1432, 1434, 1436, 1438, 1440, 1442, 1444, 1448, 1452,
       1454, 1456, 1458, 1460, 1464, 1466, 1470, 1472, 1474, 1476, 1478,
       1480, 1482, 1484, 1486, 1488, 1490, 1492, 1494, 1496, 1500],
      dtype=int32)

In [37]:
gallery_idx = np.array([i for i in range(track_test["track_test_info"].shape[0]) if i not in query_idx-1])

In [41]:
len(np.unique(np.concatenate([gallery_idx, query_idx-1])))

12180

In [42]:
track_test["track_test_info"].shape

(12180, 4)

In [39]:
np.unique(track_test["track_test_info"][gallery_idx, 2])

array([  -1,    0,    2,    4,    8,   10,   12,   14,   16,   18,   22,
         24,   26,   28,   32,   34,   36,   44,   46,   48,   50,   52,
         60,   62,   64,   66,   68,   72,   76,   78,   80,   82,   92,
         94,   96,  100,  104,  106,  110,  112,  116,  118,  120,  128,
        130,  132,  136,  142,  144,  146,  148,  150,  154,  156,  158,
        160,  162,  166,  170,  172,  174,  176,  178,  182,  184,  186,
        188,  192,  194,  196,  198,  200,  202,  204,  206,  208,  210,
        216,  218,  220,  222,  224,  226,  228,  230,  232,  236,  238,
        240,  242,  244,  248,  252,  254,  256,  258,  260,  262,  264,
        266,  268,  270,  272,  274,  276,  278,  280,  282,  284,  286,
        288,  290,  292,  294,  296,  298,  300,  302,  304,  306,  308,
        310,  312,  314,  316,  318,  320,  322,  324,  326,  328,  330,
        332,  334,  336,  340,  342,  344,  346,  348,  350,  352,  354,
        358,  362,  364,  366,  368,  370,  372,  374,  376,  378,  380,
        384,  386,  388,  390,  394,  396,  400,  402,  404,  406,  408,
        410,  412,  414,  418,  420,  422,  424,  426,  428,  430,  432,
        434,  438,  440,  442,  444,  446,  448,  450,  452,  456,  458,
        460,  462,  464,  466,  468,  470,  472,  474,  476,  478,  480,
        482,  484,  486,  488,  490,  492,  494,  496,  498,  500,  502,
        506,  508,  512,  514,  516,  518,  520,  522,  526,  530,  534,
        538,  544,  546,  548,  550,  552,  554,  556,  558,  560,  562,
        564,  566,  568,  570,  572,  574,  578,  580,  582,  584,  588,
        590,  592,  594,  596,  598,  600,  602,  604,  606,  608,  610,
        612,  614,  616,  618,  620,  622,  624,  626,  628,  630,  632,
        634,  636,  638,  642,  644,  646,  648,  650,  652,  654,  656,
        658,  662,  664,  666,  668,  670,  672,  674,  676,  678,  680,
        682,  684,  686,  688,  690,  692,  694,  696,  698,  700,  702,
        704,  706,  708,  710,  714,  716,  718,  720,  722,  724,  726,
        728,  730,  732,  734,  736,  738,  740,  742,  744,  746,  750,
        754,  756,  758,  760,  762,  764,  766,  768,  770,  772,  774,
        776,  778,  780,  784,  786,  788,  790,  792,  794,  796,  798,
        800,  802,  804,  806,  808,  810,  812,  814,  816,  818,  820,
        822,  824,  826,  828,  830,  832,  834,  838,  842,  844,  846,
        848,  850,  852,  856,  858,  860,  866,  868,  870,  872,  874,
        876,  878,  880,  884,  886,  888,  890,  892,  894,  896,  900,
        902,  904,  908,  910,  912,  914,  916,  918,  920,  922,  924,
        926,  930,  932,  934,  936,  942,  946,  948,  950,  952,  954,
        958,  960,  962,  964,  966,  968,  970,  972,  974,  976,  978,
        982,  984,  986,  988,  990,  992,  994,  996,  998, 1000, 1002,
       1004, 1008, 1010, 1012, 1014, 1016, 1018, 1020, 1022, 1024, 1026,
       1028, 1030, 1032, 1034, 1038, 1040, 1042, 1044, 1052, 1054, 1058,
       1064, 1068, 1070, 1074, 1076, 1078, 1082, 1084, 1086, 1088, 1090,
       1092, 1096, 1098, 1100, 1102, 1104, 1108, 1110, 1112, 1116, 1118,
       1120, 1122, 1124, 1126, 1128, 1130, 1132, 1134, 1136, 1142, 1144,
       1148, 1150, 1152, 1154, 1156, 1158, 1164, 1174, 1176, 1178, 1180,
       1182, 1184, 1186, 1188, 1190, 1196, 1198, 1200, 1204, 1208, 1214,
       1216, 1222, 1224, 1226, 1228, 1230, 1234, 1236, 1238, 1240, 1244,
       1248, 1250, 1254, 1258, 1260, 1262, 1264, 1266, 1268, 1270, 1272,
       1274, 1276, 1278, 1280, 1282, 1286, 1288, 1290, 1292, 1294, 1296,
       1298, 1300, 1306, 1312, 1314, 1316, 1318, 1320, 1322, 1324, 1326,
       1330, 1332, 1336, 1338, 1340, 1342, 1344, 1348, 1350, 1352, 1354,
       1358, 1360, 1362, 1364, 1366, 1368, 1370, 1372, 1376, 1378, 1380,
       1382, 1384, 1388, 1390, 1392, 1394, 1396, 1398, 1402, 1404, 1406,
       1408, 1410, 1412, 1416, 1418, 1420, 1422, 1424, 1428, 1430, 1432,
       1434, 1436, 1438, 1440, 1442, 1448, 1452, 1454, 1456, 1458, 1460,
       1464, 1466, 1470, 1472, 1474, 1476, 1478, 1480, 1482, 1484, 1486,
       1488, 1490, 1492, 1494, 1496, 1500], dtype=int32)